#!/usr/bin/env bash
set -euo pipefail

EC2_IP="${EC2_IP:?EC2_IP must be set}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/bug-daddy-key.pem}"
REMOTE="ubuntu@${EC2_IP}"
BRANCH="${BRANCH:-master}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
REMOTE_ROOT="${REMOTE_ROOT:-/home/ubuntu/repo}"
BACKEND_SERVICE="${BACKEND_SERVICE:-bug-daddy-platform-backend.service}"
AGENT_EXECUTION_LOG_SECRET="${AGENT_EXECUTION_LOG_SECRET:?AGENT_EXECUTION_LOG_SECRET must be set}"
AGENT_EXECUTION_CALLBACK_URL="${AGENT_EXECUTION_CALLBACK_URL:-https://bugdaddy.in/api}"
SECURITY_SCANNER_ACCESS_KEY_ID="${SECURITY_SCANNER_ACCESS_KEY_ID:?SECURITY_SCANNER_ACCESS_KEY_ID must be set}"
SECURITY_SCANNER_SECRET_ACCESS_KEY="${SECURITY_SCANNER_SECRET_ACCESS_KEY:?SECURITY_SCANNER_SECRET_ACCESS_KEY must be set}"
JIRA_WEBHOOK_SECRET="${JIRA_WEBHOOK_SECRET:?JIRA_WEBHOOK_SECRET must be set}"
AI_QUEUE_URL="${AI_QUEUE_URL:?AI_QUEUE_URL must be set}"
AI_QUEUE_WORKERS="${AI_QUEUE_WORKERS:-3}"
AI_QUEUE_DEFAULT_LENGTH="${AI_QUEUE_DEFAULT_LENGTH:-3}"

echo "Deploying backend (branch '${BRANCH}') to ${EC2_IP}..."

ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "${REMOTE}" \
  "BRANCH=${BRANCH} BACKEND_PORT=${BACKEND_PORT} REMOTE_ROOT=${REMOTE_ROOT} BACKEND_SERVICE=${BACKEND_SERVICE} AGENT_EXECUTION_CALLBACK_URL=${AGENT_EXECUTION_CALLBACK_URL} AGENT_EXECUTION_LOG_SECRET='${AGENT_EXECUTION_LOG_SECRET}' SECURITY_SCANNER_ACCESS_KEY_ID='${SECURITY_SCANNER_ACCESS_KEY_ID}' SECURITY_SCANNER_SECRET_ACCESS_KEY='${SECURITY_SCANNER_SECRET_ACCESS_KEY}' JIRA_WEBHOOK_SECRET='${JIRA_WEBHOOK_SECRET}' AI_QUEUE_URL='${AI_QUEUE_URL}' AI_QUEUE_WORKERS='${AI_QUEUE_WORKERS}' AI_QUEUE_DEFAULT_LENGTH='${AI_QUEUE_DEFAULT_LENGTH}' bash -s" << 'EOF'

set -euo pipefail

cd "${REMOTE_ROOT}"
git pull origin "${BRANCH}"

echo "Restarting backend..."
BACKEND_DIR="${REMOTE_ROOT}/platform/backend"
VENV_DIR="/home/ubuntu/platform/backend/venv"
cd "${BACKEND_DIR}"
"${VENV_DIR}/bin/pip" install -r requirements.txt -q

sudo tee "/etc/systemd/system/${BACKEND_SERVICE}.d/override.conf" >/dev/null <<UNIT
[Service]
WorkingDirectory=${BACKEND_DIR}
EnvironmentFile=
Environment=AWS_REGION=ap-south-1
Environment=AGENTCORE_RUNTIME_ARN=arn:aws:bedrock-agentcore:ap-south-1:105028893980:runtime/bug_daddy-IV6831D6Rs
Environment=AGENT_EXECUTION_CALLBACK_URL=${AGENT_EXECUTION_CALLBACK_URL}
Environment=AGENT_EXECUTION_LOG_SECRET=${AGENT_EXECUTION_LOG_SECRET}
Environment=SECURITY_SCANNER_ACCESS_KEY_ID=${SECURITY_SCANNER_ACCESS_KEY_ID}
Environment=SECURITY_SCANNER_SECRET_ACCESS_KEY=${SECURITY_SCANNER_SECRET_ACCESS_KEY}
Environment=JIRA_WEBHOOK_SECRET=${JIRA_WEBHOOK_SECRET}
Environment=AI_QUEUE_URL=${AI_QUEUE_URL}
Environment=AI_QUEUE_WORKERS=${AI_QUEUE_WORKERS}
Environment=AI_QUEUE_DEFAULT_LENGTH=${AI_QUEUE_DEFAULT_LENGTH}
ExecStart=
ExecStart=${VENV_DIR}/bin/python -m uvicorn main:app --host 127.0.0.1 --port ${BACKEND_PORT}
UNIT

sudo systemctl daemon-reload
sudo systemctl restart "${BACKEND_SERVICE}"

echo "Done! https://bugdaddy.in"
EOF
